### ISSUE TITLE
TODO & FIXME

### ISSUE THREAD

**Issue by lixiaoyan** [lixiaoyan/react-boilerplate#1]
- [ ] Upgrade [json5-loader](https://github.com/webpack/json5-loader) to 1.0.0.
- [ ] Make webpack less verbose.
- [ ] Add [react-storybook](https://github.com/kadirahq/react-storybook).
- [ ] Add [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard).
- [x] Add [html-loader](https://github.com/webpack/html-loader).
- [x] Fix source-map issue for production build.
- [x] Add [json5-loader](https://github.com/webpack/json5-loader).
- [x] Add HMR.
- [x] Fix bugs for [sass-lint](https://github.com/sasstools/sass-lint) & [sasslint-webpack-plugin](https://github.com/alleyinteractive/sasslint-webpack-plugin).
